Towers = {
    Cannon = {
        image = love.graphics.newImage("Images/cannon.png"),
        dmg = 10,
        firerate = 1.5,
        range = 300,
        cost = 37,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bullet",
        projectileSpeed = 700,
        splashRadius = 0,
        pierce = 0,
        rotation = 0
    },
    MultiCannon = {
        image = love.graphics.newImage("Images/multicannon.png"),
        dmg = 6,
        firerate = 3.8,
        range = 500,
        cost = 250,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bullet",
        projectileSpeed = 700,
        splashRadius = 0,
        pierce = 0,
        rotation = 0
    },
    IceTower = {
        image = love.graphics.newImage("Images/icetower.png"),
        dmg = 7,
        firerate = 1.3,
        range = 350,
        cost = 73,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"detection","slow"},
        projectile = "ice",
        projectileSpeed = 550,
        splashRadius = 65,
        pierce = 0,
        rotation = 0,
    },
    RailgunTower = {
        image = love.graphics.newImage("Images/railguntower.png"),
        dmg = 30,
        firerate = 0.55,
        range = 550,
        cost = 190,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"detection"},
        projectile = "laser",
        projectileSpeed = 3200,
        splashRadius = 0,
        pierce = 2,
        rotation = 0,
    },
    BombTower = {
        image = love.graphics.newImage("Images/bombtower.png"),
        dmg = 15,
        firerate = 1,
        range = 300,
        cost = 100,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bomb",
        projectileSpeed = 450,
        splashRadius = 100,
        pierce = 0,
        rotation = 0
    } --mby more towers in the future
}

return Towers