
Towers = {
    Cannon = {
        image = love.graphics.newImage("Images/cannon.png"),
        dmg = 10,
        firerate = 1,
        range = 300,
        cost = 50,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bullet",
        projectileSpeed = 300,
        splashRadius = 0,
        pirceing = 0,
        rotation = 0
    },
    MultiCannon = {
        image = love.graphics.newImage("Images/multicannon.png"),
        dmg = 10,
        firerate = 0.2,
        range = 500,
        cost = 200,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bullet",
        projectileSpeed = 500,
        splashRadius = 0,
        pirceing = 0,
        rotation = 0
    },
    IceTower = {
        image = love.graphics.newImage("Images/icetower.png"),
        dmg = 10,
        firerate = 1.5,
        range = 400,
        cost = 75,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"detection","slow"},
        projectile = "ice",
        projectileSpeed = 300,
        splashRadius = 2,
        pirceing = 0,
        rotation = 0,
    },
    RailgunTower = {
        image = love.graphics.newImage("Images/railguntower.png"),
        dmg = 100,
        firerate = 5,
        range = 700,
        cost = 90,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"detection"},
        projectile = "bullet",
        projectileSpeed = 300,
        splashRadius = 0,
        pirceing = 2,
        rotation = 0,
    },
    BombTower = {
        image = love.graphics.newImage("Images/bombtower.png"),
        dmg = 20,
        firerate = 2,
        range = 300,
        cost = 120,
        firstUpgrade = 30,
        upgrades = 0,
        traits = {"none"},
        projectile = "bomb",
        projectileSpeed = 300,
        splashRadius = 4,
        pirceing = 0,
        rotation = 0
    } --mby more towers in the future
}

return Towers