Level9 = {
    wave1 = { enemies = { {type = "hidden", count = 8} }, spawnRate = 0.6, reward = 150 },
    wave2 = { enemies = { {type = "hidden", count = 6}, {type = "slime", count = 6} }, spawnRate = 0.55, reward = 170 },
    wave3 = { enemies = { {type = "boneReaper", count = 3}, {type = "hidden", count = 4} }, spawnRate = 0.5, reward = 190 },
    wave4 = { enemies = { {type = "hidden", count = 6}, {type = "armoredSkeleton", count = 3} }, spawnRate = 0.5, reward = 210 },
    wave5 = { enemies = { {type = "boneReaper", count = 4}, {type = "slime", count = 4} }, spawnRate = 0.45, reward = 230 },
    wave6 = { enemies = { {type = "hidden", count = 8}, {type = "tank", count = 2} }, spawnRate = 0.45, reward = 250 },
    wave7 = { enemies = { {type = "armoredSkeleton", count = 4}, {type = "hidden", count = 6} }, spawnRate = 0.4, reward = 270 },
    wave8 = { enemies = { {type = "boneReaper", count = 5}, {type = "bigSlime", count = 2} }, spawnRate = 0.4, reward = 300 },
    wave9 = { enemies = { {type = "Hiddenboss", count = 1}, {type = "hidden", count = 5} }, spawnRate = 0.5, reward = 350 },
    wave10 = { enemies = { {type = "armoredSkeleton", count = 6}, {type = "boneReaper", count = 4} }, spawnRate = 0.4, reward = 400 },
    wave11 = { enemies = { {type = "hidden", count = 10}, {type = "tank", count = 4} }, spawnRate = 0.4, reward = 450 },
    wave12 = { enemies = { {type = "Hiddenboss", count = 1}, {type = "boneReaper", count = 4} }, spawnRate = 0.5, reward = 500 },
    wave13 = { enemies = { {type = "hidden", count = 12}, {type = "armoredSkeleton", count = 5} }, spawnRate = 0.4, reward = 560 },
    wave14 = { enemies = { {type = "tank", count = 5}, {type = "boneReaper", count = 3} }, spawnRate = 0.35, reward = 600 },
    wave15 = { enemies = { {type = "Hiddenboss", count = 1}, {type = "skeletonKing", count = 1} }, spawnRate = 0.5, reward = 700 },
    wave16 = { enemies = { {type = "hidden", count = 8}, {type = "bigSlime", count = 4}, {type = "tank", count = 2} }, spawnRate = 0.35, reward = 750 },
    wave17 = { enemies = { {type = "boneReaper", count = 6}, {type = "Hiddenboss", count = 1} }, spawnRate = 0.45, reward = 850 },
    wave18 = { enemies = { {type = "GhostPhantasm", count = 1}, {type = "hidden", count = 8} }, spawnRate = 0.55, reward = 1000 },
    wave19 = { enemies = { {type = "Hiddenboss", count = 2}, {type = "tank", count = 4} }, spawnRate = 0.5, reward = 1150 },
    wave20 = { enemies = { {type = "boneReaper", count = 6}, {type = "armoredSkeleton", count = 5} }, spawnRate = 0.4, reward = 1250 },
    wave21 = { enemies = { {type = "GhostPhantasm", count = 1}, {type = "skeletonKing", count = 1} }, spawnRate = 0.5, reward = 1400 },
    wave22 = { enemies = { {type = "Hiddenboss", count = 2}, {type = "boneReaper", count = 6} }, spawnRate = 0.5, reward = 1600 },
    wave23 = { enemies = { {type = "GhostPhantasm", count = 2}, {type = "Hiddenboss", count = 1} }, spawnRate = 0.55, reward = 1800 },
    wave24 = { enemies = { {type = "Hiddenboss", count = 2}, {type = "GhostPhantasm", count = 1}, {type = "boneReaper", count = 4} }, spawnRate = 0.55, reward = 2000 },
    wave25 = { enemies = { {type = "GhostPhantasm", count = 1}, {type = "hiddenBrainrot", count = 1}, {type = "Hiddenboss", count = 2} }, spawnRate = 0.6, reward = 2500 },
}

return Level9